    /* V0.8.1 PUBLIC CLASSROOM HOTFIX · no timeout / dedupe / kick / lobby return / mobile feedback */
    const V081={version:'0.8.1',deviceKey:'sumus.quiz.device.v081'};
    const DeviceIdentity={id:(()=>{try{let id=localStorage.getItem(V081.deviceKey);if(!id){id=`dev-${crypto?.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now().toString(36)}`;localStorage.setItem(V081.deviceKey,id)}return id}catch{return`dev-${Math.random().toString(36).slice(2)}`}})()};
    const v081Style=document.createElement('style');v081Style.textContent=`
      .v081-hide-time{display:none!important}
      #studentLabLauncher{display:none!important}
      .race-footer .footer-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}
      .player-card{position:relative}.player-kick{position:absolute;right:8px;top:8px;min-width:42px;height:28px;padding:0 8px;border:1px solid #ff727d55;border-radius:8px;background:#351b22;color:#ff9aa2;font-size:9px;font-weight:900;cursor:pointer;opacity:.86}.player-kick:hover{opacity:1;background:#4a2029}
      .student-timer-track,#studentSeconds{display:none!important}.student-game-head{padding:10px 16px 9px}.student-mini-row{justify-content:flex-end;margin-top:5px}
      .student-question-wrap{justify-content:flex-start;padding-top:12px}.student-answers{margin-top:10px!important;gap:10px}.student-answer{min-height:68px}.student-bottom-actions{padding:10px 0 2px}
      .student-result-flash{position:absolute;inset:0;z-index:80;display:grid;place-items:center;text-align:center;pointer-events:none;animation:v081Flash .56s cubic-bezier(.2,.9,.2,1) both}.student-result-flash.correct{background:radial-gradient(circle,#41f0a8ee 0,#0e8c65dd 35%,#06131cf2 78%)}.student-result-flash.wrong{background:radial-gradient(circle,#ff6678e8 0,#8c2638df 36%,#06131cf2 78%)}.student-result-flash.pass{background:radial-gradient(circle,#f4b657e8 0,#8a5c1fe0 36%,#06131cf2 78%)}.student-result-flash .mark{font-size:112px;line-height:.85;font-weight:1000;filter:drop-shadow(0 15px 28px #0008)}.student-result-flash b{display:block;margin-top:18px;font-size:34px;letter-spacing:-.04em}.student-result-flash p{margin:8px 0 0;font-size:16px;font-weight:900;color:#fff}.student-result-flash.correct .mark{animation:v081Pop .48s ease both}.student-result-flash.wrong .mark{animation:v081Shake .4s ease both}@keyframes v081Flash{0%{opacity:0}18%{opacity:1}82%{opacity:1}100%{opacity:0}}@keyframes v081Pop{0%{transform:scale(.35) rotate(-16deg)}65%{transform:scale(1.15) rotate(3deg)}100%{transform:scale(1)}}@keyframes v081Shake{0%,100%{transform:translateX(0)}25%{transform:translateX(-15px) rotate(-4deg)}50%{transform:translateX(15px) rotate(4deg)}75%{transform:translateX(-8px)}}
      .student-lobby-return{width:100%;min-height:58px;margin-top:14px;border:1px solid #5de4a85c;border-radius:12px;background:#0e332d;color:#7cf0bc;font-weight:950;letter-spacing:.06em;cursor:pointer}
      @media(max-width:430px){.student-view{padding:14px 14px 16px}.student-question-wrap{padding:9px 14px 14px}.student-prompt{margin:12px 0 10px;font-size:25px}.student-prompt.ko{font-size:21px}.student-answer{min-height:64px;padding:13px 13px}.student-characters{grid-template-columns:repeat(4,minmax(0,1fr));gap:7px}.student-character{min-width:0;min-height:74px}.student-character span{font-size:31px}.student-arena-card{padding:13px;margin-bottom:10px}}
      @media(min-height:800px) and (max-width:520px){.student-answer{min-height:72px}.student-answers{gap:11px}.student-prompt{margin-top:16px;margin-bottom:12px}}
    `;document.head.append(v081Style);

    const enforceNoLimit=()=>{state.config.timeLimit=0;const el=$('#timeLimit');if(el){el.innerHTML='<option value="0" selected>제한 없음</option>';el.value='0';el.closest('.field')?.classList.add('v081-hide-time')}};enforceNoLimit();
    const V081_applyPreset=applyPreset;applyPreset=function(id){V081_applyPreset(id);enforceNoLimit()};
    const V081_readRuleControls=readRuleControls;readRuleControls=function(){V081_readRuleControls();enforceNoLimit()};

    const V081_studentJoin=StudentApp.join.bind(StudentApp);StudentApp.join=function(name){const clean=sanitizePlayerName(name);if(!clean){StudentSession.error='이름을 입력해 주세요.';this.render();return}StudentSession.error='';LocalTransport.send('PLAYER_JOIN_REQUEST',{...EventPayload.base(),name:clean,deviceId:DeviceIdentity.id,reconnectToken:StudentSession.reconnectToken||''})};
    TeacherBridge.kickedDevices=new Set();
    const V081_teacherJoin=TeacherBridge.join.bind(TeacherBridge);TeacherBridge.join=function(message){const p=message.payload||{},name=sanitizePlayerName(p.name),deviceId=String(p.deviceId||'');if(deviceId&&this.kickedDevices.has(deviceId)){LocalTransport.send('PLAYER_JOIN_REJECTED',{...EventPayload.base(),targetClientId:message.senderId,reason:'방장에 의해 퇴장된 기기입니다. 새 방이 만들어질 때 다시 입장할 수 있습니다.'});return}const existing=state.players.find(x=>(deviceId&&x.deviceId===deviceId)||x.clientId===message.senderId);if(existing){if(name&&sanitizePlayerName(existing.name).toLowerCase()!==name.toLowerCase()){LocalTransport.send('PLAYER_JOIN_REJECTED',{...EventPayload.base(),targetClientId:message.senderId,reason:`이 기기는 이미 ${existing.name} 학생으로 입장되어 있습니다.`});return}existing.deviceId=deviceId||existing.deviceId;V061_touchPlayer(existing,message.senderId);LocalTransport.send('PLAYER_JOIN_ACCEPTED',{...EventPayload.base(existing.id),targetClientId:message.senderId,reconnectToken:existing.reconnectToken,player:studentPlayerView(existing),snapshot:battleSnapshot(message.senderId)});this.publish(message.senderId);renderLobby();return}const before=new Set(state.players.map(x=>x.id));V081_teacherJoin(message);const created=state.players.find(x=>!before.has(x.id)&&x.clientId===message.senderId);if(created)created.deviceId=deviceId};

    const resetPlayerForLobby=p=>{if(!p)return;Object.assign(p,{ready:false,status:'CONNECTING',finished:false,finishRank:0,finishAt:0,answered:0,correct:0,wrong:0,pass:0,combo:0,maxCombo:0,distance:0,worldDistance:0,displayDistance:0,targetDistance:0,times:[],speedPoints:0,normalizedScore:0,assignedTotal:0,questions:[],questionIndex:0,activeQuestionId:'',activeAttemptId:'',questionDeadlineAt:0,questionPausedRemainingMs:0});p.el=null};
    TeacherBridge.kickPlayer=function(id){const p=state.players.find(x=>x.id===id);if(!p)return;if(p.deviceId)this.kickedDevices.add(p.deviceId);LocalTransport.send('PLAYER_KICKED',{...EventPayload.base(p.id),targetClientId:p.clientId||'',reason:'방장에 의해 퇴장되었습니다.'});p.el?.remove?.();state.players=state.players.filter(x=>x.id!==id);state.race.order=state.race.order.filter(x=>x!==id);renderLobby();renderRangeRows();this.publish();toast(`${p.name} 학생을 퇴장시켰습니다.`,'warn')};
    TeacherBridge.returnAllToLobby=function(){state.race.running=false;state.race.paused=false;clearTimeout(state.race.autoTimer);state.race.autoTimer=null;cancelAnimationFrame(state.race.raf);state.players.forEach(resetPlayerForLobby);state.race.order=state.players.map(p=>p.id);LocalTransport.send('RETURN_TO_LOBBY',{...EventPayload.base(),all:true});showScreen('lobby');renderLobby();renderRangeRows();this.publish()};
    const V081_teacherHandle=TeacherBridge.handle.bind(TeacherBridge);TeacherBridge.handle=function(message){const p=message.payload||{};if(message.type==='PLAYER_RETURN_LOBBY'){const player=state.players.find(x=>x.id===p.playerId);if(!player)return;if(player.reconnectToken&&p.reconnectToken!==player.reconnectToken)return;if(state.race.running&&state.screen==='race')return;resetPlayerForLobby(player);LocalTransport.send('RETURN_TO_LOBBY',{...EventPayload.base(player.id),targetClientId:message.senderId,player:studentPlayerView(player)});renderLobby();renderRangeRows();this.publish();return}return V081_teacherHandle(message)};

