(()=>{
'use strict';
const $=id=>document.getElementById(id); const KEY='sumus_planner_pro_v2';
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'], months=['January','February','March','April','May','June','July','August','September','October','November','December'];
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; const todayISO=()=>iso(new Date()); const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
const addDays=(key,n)=>{let d=new Date(key+'T00:00:00');d.setDate(d.getDate()+n);return iso(d)}; const pretty=x=>{if(!x)return'—';let d=new Date(x+'T00:00:00');return`${months[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`};
function seed(){let t=todayISO(),tm=addDays(t,1);return{focus:0,wins:0,goals:['수업 준비 완료','루틴 4개 이상 달성','마감 작업 놓치지 않기'],tasks:[{id:uid(),name:'오늘 수업 자료 정리',due:t,priority:'High',status:'Not started',done:false},{id:uid(),name:'학생 관리 체크',due:t,priority:'Medium',status:'Not started',done:false},{id:uid(),name:'내일 준비 사항 확인',due:tm,priority:'Low',status:'Not started',done:false}],routineHistory:{},timeLogs:{}}}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)return normalize(x)}catch(e){}return seed()}
function normalize(x){x=x&&typeof x==='object'?x:seed();x.focus=Number(x.focus)||0;x.wins=Number(x.wins)||0;x.goals=Array.isArray(x.goals)?x.goals:[];x.tasks=Array.isArray(x.tasks)?x.tasks.filter(t=>t&&typeof t.name==='string'):[];x.routineHistory=x.routineHistory&&typeof x.routineHistory==='object'?x.routineHistory:{};x.timeLogs=x.timeLogs&&typeof x.timeLogs==='object'?x.timeLogs:{};return x}
let S=load(); const saveState=()=>localStorage.setItem(KEY,JSON.stringify(S));
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1300)}
function clock(){let d=new Date();$('hh').textContent=String(d.getHours()).padStart(2,'0');$('mm').textContent=String(d.getMinutes()).padStart(2,'0');$('ss').textContent=String(d.getSeconds()).padStart(2,'0');$('date').textContent=`${days[d.getDay()]} | ${months[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`}
clock();setInterval(clock,1000);
function weatherFallback(){let I=['☀️','🌤️','🌤️','🌧️','🌦️'],names=['Wed','Thu','Fri','Sat','Sun'];$('weather').innerHTML=I.map((x,i)=>`<div class="w"><i>${x}</i><span>${names[i]}</span><b>${[30,30,29,29,28][i]}°</b><span>${[23,24,23,24,24][i]}°</span></div>`).join('');$('now').textContent='23°C'}
weatherFallback();fetch('https://api.open-meteo.com/v1/forecast?latitude=37.5665&longitude=126.9780&current=temperature_2m&daily=weather_code,temperature_2m_max,temperature_2m_min&timezone=Asia%2FSeoul&forecast_days=5').then(r=>r.json()).then(j=>{if(!j.current||!j.daily)return;$('now').textContent=Math.round(j.current.temperature_2m)+'°C';let ic=c=>c===0?'☀️':c<=3?'🌤️':c<=67?'🌧️':c<=77?'🌨️':c<=82?'🌦️':'⛈️';$('weather').innerHTML=j.daily.time.map((x,i)=>{let d=new Date(x+'T00:00:00');return `<div class="w"><i>${ic(j.daily.weather_code[i])}</i><span>${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d.getDay()]}</span><b>${Math.round(j.daily.temperature_2m_max[i])}°</b><span>${Math.round(j.daily.temperature_2m_min[i])}°</span></div>`}).join('')}).catch(()=>{});
const rlabels=['☀️ 침대 정리','💧 물 마시기','🧾 오늘 회고','🧠 25분 집중','🚶 가볍게 운동','📖 독서','🌙 취침 전 일기']; let routineDate=todayISO();
function routineFor(key){if(!Array.isArray(S.routineHistory[key]))S.routineHistory[key]=Array(rlabels.length).fill(false);if(S.routineHistory[key].length!==rlabels.length)S.routineHistory[key]=Array(rlabels.length).fill(false);return S.routineHistory[key]}
function renderRoutine(){let arr=routineFor(routineDate);$('rDate').textContent=pretty(routineDate);$('routines').innerHTML=arr.map((v,i)=>`<div class="ritem"><span class="rcheck ${v?'done':''}" data-r="${i}">${v?'✓':''}</span><span class="text">${rlabels[i]}</span></div>`).join('');let n=arr.filter(Boolean).length,p=n/rlabels.length*100;$('pct').textContent=p.toFixed(1)+'%';$('bar').style.width=p+'%';saveState()}
$('rPrev').onclick=()=>{routineDate=addDays(routineDate,-1);renderRoutine()};$('rNext').onclick=()=>{routineDate=addDays(routineDate,1);renderRoutine()};$('rToday').onclick=()=>{routineDate=todayISO();renderRoutine()};
function showHistory(){let keys=Object.keys(S.routineHistory).sort().reverse();if(!keys.length){$('historyList').innerHTML='<div class="empty">아직 저장된 루틴 기록이 없어.</div>'}else{$('historyList').innerHTML=keys.map(k=>{let a=S.routineHistory[k]||[],n=a.filter(Boolean).length,p=Math.round(n/rlabels.length*100);return `<div class="history-row" data-hdate="${k}"><div class="hist-date">${pretty(k)}</div><div class="hist-score">${n}/${rlabels.length}</div><div class="hist-pct">${p}%</div></div>`}).join('')}$('historyMb').classList.add('show')}
$('routineHistoryLink').onclick=showHistory;$('historyClose').onclick=()=>$('historyMb').classList.remove('show');$('historyList').onclick=e=>{let row=e.target.closest('[data-hdate]');if(!row)return;routineDate=row.dataset.hdate;$('historyMb').classList.remove('show');renderRoutine();$('routineSection').scrollIntoView({behavior:'smooth',block:'center'})};
function pclass(p){return'p'+String(p).replace(' ','')} function sclass(s){return s==='In progress'?'sProgress':s==='Done'?'sDone':'sNot'}
function renderTasks(){S.tasks.sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));$('tasks').innerHTML=S.tasks.length?S.tasks.map(t=>`<tr><td><span class="check ${t.done?'done':''}" data-done="${t.id}">${t.done?'✓':''}</span></td><td class="taskname" data-edit="${t.id}">${escapeHtml(t.name)}</td><td>${pretty(t.due)}</td><td><span class="pill ${pclass(t.priority)}">${t.priority}</span></td><td><span class="pill ${sclass(t.status)}">${t.status}</span></td></tr>`).join(''):'<tr><td colspan="5" class="empty">아직 작업이 없어. + 작업 추가를 눌러 추가해줘.</td></tr>';renderToday();renderCal();saveState()}
function renderToday(){let td=todayISO(),a=S.tasks.filter(t=>!t.done&&t.due===td);$('today').innerHTML=a.length?a.map(t=>`<li class="todo"><span class="left"><span class="check" data-done="${t.id}"></span><span class="text taskname" data-edit="${t.id}">${escapeHtml(t.name)}</span></span><span class="chip">TODAY</span></li>`).join(''):'<li style="color:#91a5b7">오늘 할 일을 추가해줘.</li>'}
function renderGoals(){$('goals').innerHTML=S.goals.slice(0,3).map((g,i)=>`<li data-goal="${i}" class="action-link"><span class="goalnum">${i+1}</span><span class="text">${escapeHtml(g)}</span></li>`).join('')}
let edit=null;function openTask(date=todayISO(),id=null){edit=id;let t=id?S.tasks.find(x=>x.id===id):null;$('mt').textContent=t?'작업 수정':'새 작업';$('name').value=t?.name||'';$('due').value=t?.due||date;$('priority').value=t?.priority||'Medium';$('status').value=t?.status||'Not started';$('del').style.display=t?'block':'none';$('mb').classList.add('show');setTimeout(()=>$('name').focus(),50)}function closeTask(){$('mb').classList.remove('show');edit=null}
$('addTask').onclick=()=>openTask();$('addTask2').onclick=()=>openTask();$('addGoal').onclick=()=>{let x=prompt('최우선 목표를 입력해줘');if(x&&x.trim()){S.goals.unshift(x.trim());saveState();renderGoals()}};$('addSession').onclick=()=>{S.focus++;saveState();counters();toast('집중 세션 +1')};$('cancel').onclick=closeTask;$('save').onclick=()=>{let n=$('name').value.trim();if(!n)return toast('작업 이름을 입력해줘');if(edit){let t=S.tasks.find(x=>x.id===edit);if(t)Object.assign(t,{name:n,due:$('due').value,priority:$('priority').value,status:$('status').value,done:$('status').value==='Done'})}else S.tasks.push({id:uid(),name:n,due:$('due').value,priority:$('priority').value,status:$('status').value,done:$('status').value==='Done'});closeTask();renderTasks();toast('작업 저장 완료')};$('del').onclick=()=>{if(!edit)return;S.tasks=S.tasks.filter(x=>x.id!==edit);closeTask();renderTasks();toast('삭제 완료')};
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.addEventListener('click',e=>{let r=e.target.dataset.r;if(r!==undefined){let arr=routineFor(routineDate);arr[+r]=!arr[+r];renderRoutine();return}let d=e.target.dataset.done;if(d){let t=S.tasks.find(x=>x.id===d);if(t){t.done=!t.done;t.status=t.done?'Done':'Not started';renderTasks()}return}let ed=e.target.dataset.edit;if(ed){openTask(undefined,ed);return}let g=e.target.closest('[data-goal]');if(g){let i=+g.dataset.goal,n=prompt('목표 수정',S.goals[i]);if(n===null)return;if(n.trim())S.goals[i]=n.trim();else S.goals.splice(i,1);saveState();renderGoals()}});
function counters(){$('focus').textContent=`${S.focus||0}/4`;$('wins').textContent=`${S.wins||0}/50`}$('fm').onclick=()=>{S.focus=Math.max(0,S.focus-1);saveState();counters()};$('fp').onclick=()=>{S.focus++;saveState();counters()};$('wm').onclick=()=>{S.wins=Math.max(0,S.wins-1);saveState();counters()};$('wp').onclick=()=>{S.wins++;saveState();counters()};
let left=1500,run=false,int=null;function timer(){let m=Math.floor(left/60),s=left%60;$('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}timer();document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');left=+b.dataset.sec;run=false;clearInterval(int);$('play').textContent='▶';timer()});$('play').onclick=()=>{run=!run;$('play').textContent=run?'❚❚':'▶';if(run)int=setInterval(()=>{if(left>0){left--;timer()}else{clearInterval(int);run=false;$('play').textContent='▶';S.focus++;S.wins++;saveState();counters();toast('집중 세션 완료!')}},1000);else clearInterval(int)};
let logDate=todayISO();function ensureLogs(key){if(!Array.isArray(S.timeLogs[key]))S.timeLogs[key]=[];return S.timeLogs[key]}function defaultTimes(){let d=new Date(),h=d.getHours(),n=(h+1)%24;$('logStart').value=String(h).padStart(2,'0')+':00';$('logEnd').value=String(n).padStart(2,'0')+':00'}
function renderTimeLogs(){let arr=ensureLogs(logDate);$('logDate').textContent=pretty(logDate);$('timeList').innerHTML=arr.length?arr.sort((a,b)=>a.start.localeCompare(b.start)).map(x=>`<div class="time-row"><div class="time-span">${x.start}</div><div class="time-span">${x.end}</div><div class="time-desc">${escapeHtml(x.activity)}</div><div class="time-actions"><button class="icon-btn danger" data-logdel="${x.id}">삭제</button></div></div>`).join(''):'<div class="empty">이 날짜의 시간 기록이 없어.</div>';saveState()}
$('addLog').onclick=()=>{let st=$('logStart').value,en=$('logEnd').value,act=$('logActivity').value.trim();if(!st||!en||!act)return toast('시간과 내용을 모두 입력해줘');ensureLogs(logDate).push({id:uid(),start:st,end:en,activity:act});$('logActivity').value='';renderTimeLogs();toast('시간 기록 저장 완료')};$('timeList').onclick=e=>{let id=e.target.dataset.logdel;if(!id)return;S.timeLogs[logDate]=ensureLogs(logDate).filter(x=>x.id!==id);renderTimeLogs()};$('logPrev').onclick=()=>{logDate=addDays(logDate,-1);renderTimeLogs()};$('logNext').onclick=()=>{logDate=addDays(logDate,1);renderTimeLogs()};$('logToday').onclick=()=>{logDate=todayISO();renderTimeLogs()};defaultTimes();
let calDate=new Date();calDate=new Date(calDate.getFullYear(),calDate.getMonth(),1);function renderCal(){$('month').textContent=`${months[calDate.getMonth()]} ${calDate.getFullYear()}`;let first=new Date(calDate.getFullYear(),calDate.getMonth(),1),start=new Date(first);start.setDate(1-first.getDay());let h=['SUN','MON','TUE','WED','THU','FRI','SAT'].map(x=>`<div class="dow">${x}</div>`).join('');for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let key=iso(d),it=S.tasks.filter(t=>t.due===key);let rc=Array.isArray(S.routineHistory[key])?S.routineHistory[key].filter(Boolean).length:0;h+=`<div class="day ${d.getMonth()!==calDate.getMonth()?'out':''} ${key===todayISO()?'today':''}" data-date="${key}"><div class="dn">${d.getDate()}${rc?` · R${rc}/7`:''}</div>${it.slice(0,2).map(t=>`<div class="event ${t.done?'done':''}">${escapeHtml(t.name)}</div>`).join('')}</div>`}$('cal').innerHTML=h}
$('cal').onclick=e=>{let d=e.target.closest('[data-date]');if(d)openTask(d.dataset.date)};$('prev').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()-1,1);renderCal()};$('next').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()+1,1);renderCal()};$('todayMonth').onclick=()=>{let d=new Date();calDate=new Date(d.getFullYear(),d.getMonth(),1);renderCal()};
$('full').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(e){toast('브라우저에서 전체화면을 허용해줘')}};$('backup').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='sumus-planner-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
renderRoutine();renderGoals();renderTasks();counters();renderTimeLogs();renderCal();
})();