// Shared live autosave helper
function bindAutoSaveFields(ids,save,delay=450){
  let timer=null;
  const queued=()=>{clearTimeout(timer);timer=setTimeout(save,delay)};
  ids.forEach(id=>{const el=$(id);if(!el)return;el.addEventListener('input',queued);el.addEventListener('change',()=>{clearTimeout(timer);save()})});
}

// Goals
function renderGoals(){const box=$('goalList');if(!state.goals.length){box.innerHTML='<div class="empty-state">오늘 가장 중요한 목표를 추가해봐.</div>';return}box.innerHTML=state.goals.slice(0,4).map((g,i)=>`<div class="goal-row"><span class="goal-index">${i+1}</span><span class="goal-text" data-goal-edit="${g.id}">${esc(g.text)}</span><button class="mini-delete" data-goal-del="${g.id}">×</button></div>`).join('')}
function openGoal(id=null){let live=id?state.goals.find(x=>x.id===id):null;modal(`<h3>${live?'목표 수정':'최우선 목표 추가'}</h3><div class="field"><label>목표</label><input id="mGoal" value="${esc(live?.text||'')}" placeholder="예: 오늘 수업자료 완성"></div><div class="autosave-note">입력 내용은 자동 저장돼. 완료 버튼은 닫기 용도야.</div>${modalActions(live?'<button class="danger-button" data-delete>삭제</button>':'')}`,()=>{const save=()=>{const text=$('mGoal').value.trim();if(!text)return;if(live){live.text=text;live.updatedAt=nowStamp()}else{live={id:uid(),text,updatedAt:nowStamp()};state.goals.unshift(live)}markChanged();renderGoals()};$('mGoal').focus();bindAutoSaveFields(['mGoal'],save);$('modal').querySelector('[data-save]').onclick=()=>{save();closeModal()};const del=$('modal').querySelector('[data-delete]');if(del)del.onclick=()=>{state.goals=state.goals.filter(x=>x.id!==live?.id);markChanged();renderGoals();closeModal()}})}
$('addGoalBtn').onclick=()=>openGoal();document.addEventListener('click',e=>{const id=e.target.dataset.goalEdit;if(id)openGoal(id);const d=e.target.dataset.goalDel;if(d){state.goals=state.goals.filter(x=>x.id!==d);markChanged();renderGoals()}});

let taskFilter='active';$('taskFilter').onchange=e=>{taskFilter=e.target.value;renderTasks()};
function renderTasks(){const today=todayISO();const active=state.tasks.filter(t=>!t.deleted);const todayList=active.filter(t=>t.due===today&&!t.done).sort((a,b)=>(a.priorityRank||0)-(b.priorityRank||0));$('todayTasks').innerHTML=todayList.length?todayList.map(t=>`<div class="task-row"><span class="check ${t.done?'done':''}" data-task-check="${t.id}">${t.done?'✓':''}</span><span class="task-name" data-task-edit="${t.id}">${esc(t.name)}</span><span class="task-chip">TODAY</span></div>`).join(''):'<div class="empty-state">오늘 할 일이 없어. + 추가로 넣어봐.</div>';let rows=active.filter(t=>taskFilter==='all'||(taskFilter==='done'?t.done:!t.done)).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));$('taskTableBody').innerHTML=rows.length?rows.map(t=>`<tr><td><span class="check ${t.done?'done':''}" data-task-check="${t.id}">${t.done?'✓':''}</span></td><td><span class="task-name" data-task-edit="${t.id}">${esc(t.name)}</span></td><td>${t.due?shortDate(t.due):'—'}</td><td><span class="pill p-${esc(t.priority)}">${esc(t.priority)}</span></td><td><span class="pill s-${esc(t.status)}">${esc(t.status)}</span></td><td><div class="row-actions"><button data-task-edit="${t.id}">✎</button><button data-task-del="${t.id}">×</button></div></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty-state">표시할 작업이 없어.</div></td></tr>';renderMonth()}
function openTask(id=null,date=todayISO()){let live=id?state.tasks.find(x=>x.id===id):null;modal(`<h3>${live?'작업 수정':'새 작업'}</h3><div class="form-grid"><div class="field"><label>작업 이름</label><input id="mTaskName" value="${esc(live?.name||'')}" placeholder="무엇을 해야 하나요?"></div><div class="form-row"><div class="field"><label>마감일</label><input id="mTaskDue" type="date" value="${esc(live?.due||date)}"></div><div class="field"><label>우선순위</label><select id="mTaskPriority">${['Low','Medium','High','Urgent'].map(x=>`<option ${x===(live?.priority||'Medium')?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="field"><label>상태</label><select id="mTaskStatus">${['Not started','In progress','Done'].map(x=>`<option ${x===(live?.status||'Not started')?'selected':''}>${x}</option>`).join('')}</select></div><div class="autosave-note">작업 이름을 입력하는 순간부터 자동 저장돼.</div></div>${modalActions(live?'<button class="danger-button" data-delete>삭제</button>':'')}`,()=>{const save=()=>{const name=$('mTaskName').value.trim();if(!name)return;const status=$('mTaskStatus').value;const data={name,due:$('mTaskDue').value,priority:$('mTaskPriority').value,status,done:status==='Done',updatedAt:nowStamp()};if(live)Object.assign(live,data);else{live={id:uid(),...data};state.tasks.push(live)}markChanged();renderTasks()};$('mTaskName').focus();bindAutoSaveFields(['mTaskName','mTaskDue','mTaskPriority','mTaskStatus'],save);$('modal').querySelector('[data-save]').onclick=()=>{save();closeModal()};const del=$('modal').querySelector('[data-delete]');if(del)del.onclick=()=>{if(live){live.deleted=true;live.updatedAt=nowStamp();markChanged();renderTasks()}closeModal()}})}
$('addTaskBtn').onclick=()=>openTask();$('addTaskTop').onclick=()=>openTask();$('quickTask').onclick=()=>openTask();document.addEventListener('click',e=>{const check=e.target.dataset.taskCheck;if(check){const t=state.tasks.find(x=>x.id===check);if(t){t.done=!t.done;t.status=t.done?'Done':'Not started';t.updatedAt=nowStamp();markChanged();renderTasks()}return}const edit=e.target.dataset.taskEdit;if(edit){openTask(edit);return}const del=e.target.dataset.taskDel;if(del){const t=state.tasks.find(x=>x.id===del);if(t){t.deleted=true;t.updatedAt=nowStamp();markChanged();renderTasks()}}});
