// Daily time logs
let logDate=todayISO();function logsFor(date){if(!state.timeLogs[date])state.timeLogs[date]=[];return state.timeLogs[date]}
function defaultLogTimes(){const d=new Date(),h=d.getHours();$('logStart').value=`${pad(h)}:00`;$('logEnd').value=`${pad((h+1)%24)}:00`}
function renderLogs(){$('logToday').textContent=koDate(logDate);const rows=logsFor(logDate).filter(x=>!x.deleted).sort((a,b)=>a.start.localeCompare(b.start));$('timeLogList').innerHTML=rows.length?rows.map(x=>`<div class="time-log-row"><span class="time-log-time">${x.start} ~ ${x.end}</span><span class="time-log-activity" data-log-edit="${x.id}">${esc(x.activity)}</span><button data-log-del="${x.id}">×</button></div>`).join(''):'<div class="empty-state">이 날짜의 시간 기록이 없어.</div>'}
let activeLogDraftId=null,logAutoTimer=null;
function autoSaveLogForm(){const st=$('logStart').value,en=$('logEnd').value,activity=$('logActivity').value.trim();if(!st||!en||!activity)return null;let l=activeLogDraftId?logsFor(logDate).find(x=>x.id===activeLogDraftId&&!x.deleted):null;if(l){l.start=st;l.end=en;l.activity=activity;l.updatedAt=nowStamp()}else{l={id:uid(),start:st,end:en,activity,updatedAt:nowStamp()};logsFor(logDate).push(l);activeLogDraftId=l.id}markChanged();renderLogs();return l}
function queueLogAutosave(){clearTimeout(logAutoTimer);logAutoTimer=setTimeout(autoSaveLogForm,650)}
function addLogFromForm(){const l=autoSaveLogForm();if(!l)return toast('시간과 내용을 모두 입력해줘');$('logActivity').value='';activeLogDraftId=null;renderLogs();toast('시간 기록 저장됨 ✓')}
$('addLogBtn').onclick=addLogFromForm;$('logActivity').addEventListener('input',queueLogAutosave);$('logActivity').addEventListener('keydown',e=>{if(e.key==='Enter')addLogFromForm()});$('logStart').addEventListener('change',()=>{if($('logActivity').value.trim())autoSaveLogForm()});$('logEnd').addEventListener('change',()=>{if($('logActivity').value.trim())autoSaveLogForm()});$('logPrev').onclick=()=>{logDate=addDays(logDate,-1);activeLogDraftId=null;$('logActivity').value='';renderLogs()};$('logNext').onclick=()=>{logDate=addDays(logDate,1);activeLogDraftId=null;$('logActivity').value='';renderLogs()};$('logToday').onclick=()=>{logDate=todayISO();activeLogDraftId=null;$('logActivity').value='';renderLogs()};$('quickTimeLog').onclick=()=>{$('logActivity').focus();$('logActivity').scrollIntoView({behavior:'smooth',block:'center'})};
function openLogEdit(id){const l=logsFor(logDate).find(x=>x.id===id);if(!l)return;modal(`<h3>시간 기록 수정</h3><div class="form-row"><div class="field"><label>시작</label><input id="mLogStart" type="time" value="${l.start}"></div><div class="field"><label>종료</label><input id="mLogEnd" type="time" value="${l.end}"></div></div><div class="field"><label>한 일</label><input id="mLogActivity" value="${esc(l.activity)}"></div><div class="autosave-note">수정하는 즉시 자동 저장돼.</div>${modalActions('<button class="danger-button" data-delete>삭제</button>')}`,()=>{const save=()=>{l.start=$('mLogStart').value;l.end=$('mLogEnd').value;l.activity=$('mLogActivity').value.trim();l.updatedAt=nowStamp();markChanged();renderLogs()};bindAutoSaveFields(['mLogStart','mLogEnd','mLogActivity'],save);$('modal').querySelector('[data-save]').onclick=()=>{save();closeModal()};$('modal').querySelector('[data-delete]').onclick=()=>{l.deleted=true;l.updatedAt=nowStamp();markChanged();renderLogs();closeModal()}})}
document.addEventListener('click',e=>{const edit=e.target.dataset.logEdit;if(edit)openLogEdit(edit);const del=e.target.dataset.logDel;if(del){const l=logsFor(logDate).find(x=>x.id===del);if(l){l.deleted=true;l.updatedAt=nowStamp();markChanged();renderLogs()}}});
