// Focus & timer
function renderFocus(){$('focusCount').textContent=state.focus.sessions;$('winsCount').textContent=state.focus.wins}
function bumpFocus(k,d){state.focus[k]=Math.max(0,(state.focus[k]||0)+d);state.focus.updatedAt=nowStamp();markChanged();renderFocus()}
$('focusMinus').onclick=()=>bumpFocus('sessions',-1);$('focusPlus').onclick=()=>bumpFocus('sessions',1);$('winsMinus').onclick=()=>bumpFocus('wins',-1);$('winsPlus').onclick=()=>bumpFocus('wins',1);
let timerSeconds=25*60,timerRunning=false,timerHandle=null;function renderTimer(){const m=Math.floor(timerSeconds/60),s=timerSeconds%60;$('timerDisplay').textContent=`${pad(m)}:${pad(s)}`;$('timerToggle').textContent=timerRunning?'❚❚ 일시정지':'▶ 시작'}
function stopTimer(){clearInterval(timerHandle);timerHandle=null;timerRunning=false;renderTimer()}
$('timerToggle').onclick=()=>{timerRunning=!timerRunning;if(timerRunning){timerHandle=setInterval(()=>{timerSeconds--;if(timerSeconds<=0){stopTimer();state.focus.sessions++;state.focus.wins++;state.focus.updatedAt=nowStamp();state.pomodoroHistory.push({id:uid(),date:todayISO(),completedAt:new Date().toISOString(),updatedAt:nowStamp()});markChanged();renderFocus();toast('집중 세션 완료!')}renderTimer()},1000)}else stopTimer();renderTimer()};document.querySelectorAll('.timer-tabs button').forEach(b=>b.onclick=()=>{stopTimer();document.querySelectorAll('.timer-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');timerSeconds=Number(b.dataset.min)*60;renderTimer()});renderTimer();

let weekOffset=0;const dayNames=['일','월','화','수','목','금','토'];function weekStartFor(offset=0){const d=new Date();const day=d.getDay();d.setHours(0,0,0,0);d.setDate(d.getDate()-day+(offset*7));return d}
function minutes(t){const [h,m]=t.split(':').map(Number);return h*60+m}
function renderWeek(){const start=weekStartFor(weekOffset),end=new Date(start);end.setDate(end.getDate()+6);$('weekLabel').textContent=`${start.getMonth()+1}/${start.getDate()} ~ ${end.getMonth()+1}/${end.getDate()}`;let html='<div class="corner"></div>';for(let d=0;d<7;d++){const cur=new Date(start);cur.setDate(start.getDate()+d);html+=`<div class="day-head ${iso(cur)===todayISO()?'today':''}">${dayNames[d]}<br>${cur.getMonth()+1}/${cur.getDate()}</div>`}for(let h=5;h<24;h++){html+=`<div class="time-cell">${pad(h)}:00</div>`;for(let d=0;d<7;d++)html+='<div class="slot"></div>'}html+='<div class="schedule-layer" id="scheduleLayer"></div>';$('weekGrid').innerHTML=html;const layer=$('scheduleLayer');const visible=state.weeklySchedule.filter(x=>!x.deleted);visible.forEach(s=>{const startMin=minutes(s.start),endMin=minutes(s.end);if(endMin<=300||startMin>=1440)return;const top=((Math.max(startMin,300)-300)/60)*54;const height=Math.max(26,((Math.min(endMin,1440)-Math.max(startMin,300))/60)*54);const w=100/7;const el=document.createElement('div');el.className=`schedule-block cat-${s.category||'other'}`;el.style.left=`calc(${s.day*w}% + 4px)`;el.style.width=`calc(${w}% - 8px)`;el.style.top=top+'px';el.style.height=height+'px';el.dataset.scheduleEdit=s.id;el.title=[s.title,`${s.start}~${s.end}`,s.details||''].filter(Boolean).join('\n');el.innerHTML=`<b>${esc(s.title)}</b><small>${s.start}~${s.end}</small>${s.details?`<span style="display:block;margin-top:4px;font-size:8px;line-height:1.35;opacity:.86;white-space:pre-line">${esc(s.details)}</span>`:''}`;layer.appendChild(el)})}
function openSchedule(id=null){const s=id?state.weeklySchedule.find(x=>x.id===id):null;modal(`<h3>${s?'시간표 수정':'주간 일정 추가'}</h3><div class="form-grid"><div class="field"><label>일정 이름</label><input id="mSchTitle" value="${esc(s?.title||'')}" placeholder="예: 중3 수업"></div><div class="field"><label>상세 계획 · 뭘 할지</label><textarea id="mSchDetails" rows="5" placeholder="예: 중3 문법 3과 설명 / 숙제 검사 / 단어시험 / 오답 정리">${esc(s?.details||'')}</textarea></div><div class="form-row"><div class="field"><label>요일</label><select id="mSchDay">${dayNames.map((x,i)=>`<option value="${i}" ${i===(s?.day??1)?'selected':''}>${x}요일</option>`).join('')}</select></div><div class="field"><label>구분</label><select id="mSchCat">${[['class','수업'],['work','업무'],['study','공부'],['personal','개인'],['other','기타']].map(([v,l])=>`<option value="${v}" ${v===(s?.category||'class')?'selected':''}>${l}</option>`).join('')}</select></div></div><div class="form-row"><div class="field"><label>시작</label><input id="mSchStart" type="time" value="${s?.start||'16:30'}"></div><div class="field"><label>종료</label><input id="mSchEnd" type="time" value="${s?.end||'18:00'}"></div></div></div>${modalActions(s?'<button class="danger-button" data-delete>삭제</button>':'')}`,()=>{$('mSchTitle').focus();$('modal').querySelector('[data-save]').onclick=()=>{const title=$('mSchTitle').value.trim();if(!title)return toast('일정 이름을 입력해줘');const data={title,details:$('mSchDetails').value.trim(),day:Number($('mSchDay').value),category:$('mSchCat').value,start:$('mSchStart').value,end:$('mSchEnd').value,updatedAt:nowStamp()};if(s)Object.assign(s,data);else state.weeklySchedule.push({id:uid(),...data});markChanged();renderWeek();renderMonth();closeModal()};const del=$('modal').querySelector('[data-delete]');if(del)del.onclick=()=>{s.deleted=true;s.updatedAt=nowStamp();markChanged();renderWeek();renderMonth();closeModal()}})}
$('addScheduleBtn').onclick=()=>openSchedule();$('quickSchedule').onclick=()=>openSchedule();$('weekPrev').onclick=()=>{weekOffset--;renderWeek()};$('weekNext').onclick=()=>{weekOffset++;renderWeek()};$('scheduleTodayBtn').onclick=()=>{weekOffset=0;renderWeek()};document.addEventListener('click',e=>{const id=e.target.closest('[data-schedule-edit]')?.dataset.scheduleEdit;if(id)openSchedule(id)});
