// Beauty procedure records
const BEAUTY_SEED=[
  {id:'beauty-20250702-core',name:'코어 스킨보톡스',amount:86900,hospital:'미확인',category:'보톡스',date:'2025-07-02',volume:'',memo:'',updatedAt:nowStamp()},
  {id:'beauty-20250715-rejuran',name:'리쥬란힐러',amount:196900,hospital:'미확인',category:'스킨부스터',date:'2025-07-15',volume:'2CC',memo:'',updatedAt:nowStamp()},
  {id:'beauty-20250826-rejeban',name:'리제반 2CC + 크라이오 + 파워덤보톡스',amount:136400,hospital:'미확인',category:'기타',date:'2025-08-26',volume:'',memo:'리제반 2CC · 크라이오 · 파워덤보톡스 / 개별 가격 없이 3개 시술 합산 가격',updatedAt:nowStamp()},
  {id:'beauty-20251001-rizne',name:'리즈네',amount:328900,hospital:'미확인',category:'스킨부스터',date:'2025-10-01',volume:'4CC',memo:'',updatedAt:nowStamp()},
  {id:'beauty-20251202-dual',name:'듀얼 스킨톡스(국산)',amount:97900,hospital:'뷰티온의원 안산중앙점',category:'보톡스',date:'2025-12-02',volume:'',memo:'연말감사제',updatedAt:nowStamp()},
  {id:'beauty-20251202-juvelook',name:'쥬베룩',amount:283800,hospital:'뷰티온의원 안산중앙점',category:'스킨부스터',date:'2025-12-02',volume:'2CC × 2',memo:'연말감사제',updatedAt:nowStamp()},
  {id:'beauty-20260210-jaw',name:'사각턱보톡스(국산)',amount:15400,hospital:'뷰티온의원 안산중앙점',category:'보톡스',date:'2026-02-10',volume:'50U',memo:'',updatedAt:nowStamp()},
  {id:'beauty-20260210-skin',name:'쥬베룩 스킨',amount:308000,hospital:'뷰티온의원 안산중앙점',category:'스킨부스터',date:'2026-02-10',volume:'4CC',memo:'',updatedAt:nowStamp()},
  {id:'beauty-20260609-wrinkle',name:'국산 주름보톡스',amount:44000,hospital:'뷰티온의원 안산중앙점',category:'보톡스',date:'2026-06-09',volume:'3부위',memo:'',updatedAt:nowStamp()},
  {id:'beauty-20260609-water',name:'물광톡스',amount:119900,hospital:'뷰티온의원 안산중앙점',category:'보톡스',date:'2026-06-09',volume:'',memo:'여름맞이',updatedAt:nowStamp()},
  {id:'beauty-20260609-volume',name:'쥬베룩 스킨/볼륨',amount:211000,hospital:'뷰티온의원 안산중앙점',category:'스킨부스터',date:'2026-06-09',volume:'4CC',memo:'여름맞이',updatedAt:nowStamp()}
];
const cloneBeautySeed=()=>BEAUTY_SEED.map(x=>({...x}));
const _normalizeStateWithBeauty=normalizeState;
normalizeState=function(s){s=_normalizeStateWithBeauty(s);if(!Array.isArray(s.procedures))s.procedures=cloneBeautySeed();return s};
if(!Array.isArray(state.procedures)){state.procedures=cloneBeautySeed();saveLocal();dirty=true}

let beautyView='default';
let beautyMonthDate=new Date();
function beautyMoney(n){return Number(n||0).toLocaleString('ko-KR')+'원'}
function beautyCatClass(cat){return cat==='보톡스'?'beauty-botox':cat==='스킨부스터'?'beauty-booster':'beauty-other'}
function activeProcedures(){return (state.procedures||[]).filter(x=>!x.deleted)}
function beautySorted(mode=beautyView){const rows=[...activeProcedures()];rows.sort((a,b)=>mode==='all'?String(a.date||'').localeCompare(String(b.date||'')):String(b.date||'').localeCompare(String(a.date||'')));return rows}
function renderBeautyTable(){const body=$('beautyTableBody');if(!body)return;const rows=beautySorted();body.innerHTML=rows.length?rows.map(p=>`<tr><td><span class="beauty-name" data-beauty-edit="${p.id}">${esc(p.name)}</span></td><td class="beauty-money">${Number(p.amount||0).toLocaleString('ko-KR')}</td><td>${esc(p.hospital||'')}</td><td><span class="beauty-category ${beautyCatClass(p.category)}">${esc(p.category||'기타')}</span></td><td>${esc(p.date||'')}</td><td>${esc(p.volume||'')}</td><td><div class="beauty-note-preview" title="${esc(p.memo||'')}">${esc(p.memo||'')}</div></td><td><button class="mini-delete" data-beauty-delete="${p.id}" title="삭제">×</button></td></tr>`).join(''):`<tr><td colspan="8"><div class="beauty-empty">아직 시술 기록이 없어.</div></td></tr>`;const total=activeProcedures().reduce((sum,p)=>sum+Number(p.amount||0),0);$('beautyTotal').textContent=`누적 ${beautyMoney(total)}`}
function renderBeautyCalendar(){const grid=$('beautyCalendarGrid');if(!grid)return;const y=beautyMonthDate.getFullYear(),m=beautyMonthDate.getMonth();$('beautyMonthLabel').textContent=`${y}년 ${m+1}월`;const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());const dows=['일','월','화','수','목','금','토'];let html=dows.map(x=>`<div class="beauty-cal-dow">${x}</div>`).join('');for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const date=iso(d);const events=activeProcedures().filter(p=>p.date===date);html+=`<div class="beauty-cal-day ${d.getMonth()!==m?'out':''} ${date===todayISO()?'today':''}"><div class="beauty-day-num">${d.getDate()}</div>${events.map(p=>`<div class="beauty-event ${p.category==='스킨부스터'?'booster':p.category==='기타'?'other':''}" data-beauty-edit="${p.id}" title="${esc(p.name)} · ${beautyMoney(p.amount)}">${esc(p.name)}</div>`).join('')}</div>`}grid.innerHTML=html}
function setBeautyView(view){beautyView=view;document.querySelectorAll('.beauty-tab').forEach(b=>b.classList.toggle('active',b.dataset.beautyView===view));$('beautyTableView').classList.toggle('hidden',view==='calendar');$('beautyCalendarView').classList.toggle('hidden',view!=='calendar');if(view==='calendar')renderBeautyCalendar();else renderBeautyTable()}
function renderProcedures(){if(!$('beautySection'))return;renderBeautyTable();setBeautyView(beautyView)}
function openBeautyProcedure(id=null){const p=id?activeProcedures().find(x=>x.id===id):null;modal(`<h3>${p?'시술 내역 수정':'시술 내역 추가'}</h3><div class="form-grid"><div class="field"><label>시술명</label><input id="mBeautyName" value="${esc(p?.name||'')}" placeholder="예: 쥬베룩 스킨"></div><div class="form-row"><div class="field"><label>금액</label><input id="mBeautyAmount" type="number" min="0" step="100" value="${Number(p?.amount||0)||''}" placeholder="예: 308000"></div><div class="field"><label>시술일</label><input id="mBeautyDate" type="date" value="${p?.date||todayISO()}"></div></div><div class="form-row"><div class="field"><label>병원</label><input id="mBeautyHospital" value="${esc(p?.hospital||'')}" placeholder="병원명"></div><div class="field"><label>분류</label><select id="mBeautyCategory">${['보톡스','스킨부스터','기타'].map(x=>`<option ${x===(p?.category||'기타')?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="field"><label>용량·부위</label><input id="mBeautyVolume" value="${esc(p?.volume||'')}" placeholder="예: 4CC, 50U, 3부위"></div><div class="field"><label>이벤트·비고</label><textarea id="mBeautyMemo" class="beauty-modal-note" placeholder="이벤트명, 구성, 가격 메모 등을 자유롭게 적어줘">${esc(p?.memo||'')}</textarea><div class="beauty-hint">작성 내용은 다른 기록과 동일하게 자동 저장·클라우드 동기화돼.</div></div></div>${modalActions(p?'<button class="danger-button" data-beauty-modal-delete>삭제</button>':'')}`,()=>{$('mBeautyName').focus();$('modal').querySelector('[data-save]').onclick=()=>{const name=$('mBeautyName').value.trim();if(!name)return toast('시술명을 입력해줘');const data={name,amount:Math.max(0,Number($('mBeautyAmount').value)||0),hospital:$('mBeautyHospital').value.trim(),category:$('mBeautyCategory').value,date:$('mBeautyDate').value,volume:$('mBeautyVolume').value.trim(),memo:$('mBeautyMemo').value.trim(),updatedAt:nowStamp()};if(p)Object.assign(p,data);else state.procedures.push({id:uid(),...data});markChanged();renderProcedures();closeModal();toast(p?'시술 내역 수정 완료':'시술 내역 추가 완료')};const del=$('modal').querySelector('[data-beauty-modal-delete]');if(del)del.onclick=()=>{p.deleted=true;p.updatedAt=nowStamp();markChanged();renderProcedures();closeModal();toast('시술 내역 삭제됨')}})}
$('addBeautyBtn').onclick=()=>openBeautyProcedure();
document.querySelectorAll('.beauty-tab').forEach(b=>b.onclick=()=>setBeautyView(b.dataset.beautyView));
$('beautyMonthPrev').onclick=()=>{beautyMonthDate=new Date(beautyMonthDate.getFullYear(),beautyMonthDate.getMonth()-1,1);renderBeautyCalendar()};
$('beautyMonthNext').onclick=()=>{beautyMonthDate=new Date(beautyMonthDate.getFullYear(),beautyMonthDate.getMonth()+1,1);renderBeautyCalendar()};
$('beautyMonthToday').onclick=()=>{beautyMonthDate=new Date();renderBeautyCalendar()};
document.addEventListener('click',e=>{const edit=e.target.closest('[data-beauty-edit]')?.dataset.beautyEdit;if(edit){openBeautyProcedure(edit);return}const del=e.target.closest('[data-beauty-delete]')?.dataset.beautyDelete;if(del){const p=activeProcedures().find(x=>x.id===del);if(p&&confirm(`'${p.name}' 기록을 삭제할까?`)){p.deleted=true;p.updatedAt=nowStamp();markChanged();renderProcedures()}}});
