import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';
import worker,{commit} from '../worker/index.ts';
const hash=async s=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).toString('hex');
function database(){const sqlite=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')))sqlite.exec(fs.readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));const db={prepare(sql){let values=[];return{bind(...v){values=v;return this;},async first(){return sqlite.prepare(sql).get(...values)||null;},async all(){return {results:sqlite.prepare(sql).all(...values)};},execute(){return {results:sqlite.prepare(sql).all(...values)};}};},async batch(statements){sqlite.exec('BEGIN');try{const r=statements.map(s=>s.execute());sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};return {db,sqlite};}
const state=()=>({schemaVersion:6,items:[{id:'real-code',purchasePrice:50000,actualPrice:0,saleDate:'',inventoryStatus:'재고',name:'Original'}],settings:{feeRate:.035},accounts:[],debts:[]});
async function environment(){const {db,sqlite}=database();const objects=new Map();return {sqlite,env:{DB:db,DEAL_HUNTER_ACCESS_HASH:await hash('unit-code'),FILE_SIGNING_KEY:'unit-file-key',ASSETS:{fetch:async()=>new Response('static')},BUCKET:{async put(k,b,meta){objects.set(k,{bytes:Buffer.from(b),...meta});},async get(k){const o=objects.get(k);return o?{body:o.bytes,httpMetadata:o.httpMetadata}:null;}}}};}
const request=(route,method='GET',data,code='unit-code')=>new Request('https://unit.example/api/cloud?route='+encodeURIComponent(route),{method,headers:{'x-deal-code':code,...(data?{'content-type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});
test('native cloud API preserves empty storage and blocks invalid authentication and origins',async()=>{const {env,sqlite}=await environment();assert.equal((await worker.fetch(request('state','GET',null,'wrong'),env)).status,401);const cross=request('state');cross.headers.set('origin','https://other.example');assert.equal((await worker.fetch(cross,env)).status,403);assert.equal((await worker.fetch(request('state'),env)).status,404);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM ledger').get().n,0);});
test('D1 compare-and-swap atomically allows one writer and snapshots the exact previous ledger',async()=>{const {env,sqlite}=await environment();const original=state();assert.equal((await commit(env.DB,0,original)).revision,1);const changes=[{...original,items:[{...original.items[0],name:'A'}]},{...original,items:[{...original.items[0],name:'B'}]}];const results=await Promise.all(changes.map(s=>commit(env.DB,1,s)));assert.equal(results.filter(r=>!r.conflict).length,1);assert.equal(results.filter(r=>r.conflict).length,1);assert.deepEqual(JSON.parse(sqlite.prepare('SELECT state_json FROM ledger_versions WHERE revision=1').get().state_json),original);assert.equal(sqlite.prepare('SELECT revision FROM ledger').get().revision,2);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM ledger_versions').get().n,1);});
test('restore keeps a pre-restore snapshot, refuses missing versions and stale revisions',async()=>{const {env,sqlite}=await environment();const original=state();await commit(env.DB,0,original);await commit(env.DB,1,{...original,items:[]});const id=sqlite.prepare('SELECT id FROM ledger_versions WHERE revision=1').get().id;assert((await commit(env.DB,2,null,999)).missing);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM ledger_versions').get().n,1);const result=await commit(env.DB,2,null,id);assert.deepEqual(result.state,original);assert.equal(result.revision,3);assert.equal(JSON.parse(sqlite.prepare('SELECT state_json FROM ledger_versions WHERE revision=2').get().state_json).items.length,0);assert((await commit(env.DB,2,null,id)).conflict);});
test('D1 batch rollback preserves ledger when snapshot insert fails',async()=>{const {env,sqlite}=await environment();const original=state();await commit(env.DB,0,original);sqlite.exec("CREATE TRIGGER reject_snapshot BEFORE INSERT ON ledger_versions BEGIN SELECT RAISE(ABORT,'storage failure'); END;");await assert.rejects(commit(env.DB,1,{...original,items:[]}));assert.equal(sqlite.prepare('SELECT revision FROM ledger').get().revision,1);assert.deepEqual(JSON.parse(sqlite.prepare('SELECT state_json FROM ledger').get().state_json),original);});
test('native cloud API refuses bad money, duplicate IDs and revision values',async()=>{const {env}=await environment();for(const body of [{expectedRevision:0,state:{...state(),items:[state().items[0],state().items[0]]}},{expectedRevision:0,state:{...state(),items:[{id:'x',purchasePrice:-1}]}},{expectedRevision:1.1,state:state()}])assert.equal((await worker.fetch(request('state','PUT',body),env)).status,400);assert.equal((await worker.fetch(request('state','PUT',{expectedRevision:0,state:state()}),env)).status,200);assert.equal((await worker.fetch(request('state','PUT',{expectedRevision:0,state:state()}),env)).status,409);});
test('R2 photo bytes round-trip privately; forged links, expired links and DELETE are refused',async()=>{const {env}=await environment();const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a4U0AAAAASUVORK5CYII=','base64');const form=new FormData();form.set('file',new File([png],'actual.png',{type:'image/png'}));const uploaded=await worker.fetch(new Request('https://unit.example/api/cloud?route=files',{method:'POST',headers:{'x-deal-code':'unit-code'},body:form}),env);assert.equal(uploaded.status,200);const data=await uploaded.json();const raw=await worker.fetch(new Request(data.url),env);assert.equal(raw.status,200);assert.deepEqual(Buffer.from(await raw.arrayBuffer()),png);const forged=new URL(data.url);forged.searchParams.set('sig','invalid');assert.equal((await worker.fetch(new Request(forged),env)).status,403);const expired=new URL(data.url);expired.searchParams.set('expires','1');assert.equal((await worker.fetch(new Request(expired),env)).status,403);assert.equal((await worker.fetch(request('files','DELETE'),env)).status,405);assert.equal((await worker.fetch(request('files/sign','POST',{keys:['other/photo']}),env)).status,400);});
