import {useMemo,useState} from 'react';
import {holdingDays,priceComparison} from './state';
type Product={id:string;name:string;brand:string;acquiredDate:string;expectedPrice:number;minimumPrice:number;purchasePrice:number;buyShipping:number;repairCost:number;inventoryStatus:string;archivedAt:string;listing:{price:number};priceHistory?:{from:number;to:number;at:string}[];priceCuts:number};
const won=(n:number)=>`${Math.round(n).toLocaleString('ko-KR')}원`;
export function Pricing({items,feeRate,shipping,onApply}:{items:Product[];feeRate:number;shipping:number;onApply:(drafts:Record<string,number>,ids:string[])=>void}) {
  const [threshold,setThreshold]=useState(30),[search,setSearch]=useState(''),[drafts,setDrafts]=useState<Record<string,number>>({}),[selected,setSelected]=useState<string[]>([]),[percent,setPercent]=useState(10),[preview,setPreview]=useState(false);
  const stock=items.filter(i=>!i.archivedAt&&['재고','등록대기','판매중','예약중'].includes(i.inventoryStatus));
  const visible=stock.filter(i=>(holdingDays(i.acquiredDate)??-1)>=threshold&&`${i.brand} ${i.name} ${i.id}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(holdingDays(b.acquiredDate)??-1)-(holdingDays(a.acquiredDate)??-1));
  const picked=useMemo(()=>stock.filter(i=>selected.includes(i.id)),[items,selected]);
  const locked=import.meta.env.VITE_ENABLE_PRICE_CHANGES!=='true';
  const invalid=picked.some(i=>!Number.isFinite(drafts[i.id])||drafts[i.id]<=0);
  return <><div className="simple-head"><div><p className="eyebrow">INVENTORY REVIEW</p><h1>가격·장기재고</h1><p>매입일이 확인된 재고만 보유기간을 계산합니다.</p></div><span className="price-lock">가격 적용 보류 중</span></div>
    <div className="age-grid">{[30,60,90,120].map(n=>{const rows=stock.filter(i=>(holdingDays(i.acquiredDate)??-1)>=n);return <button key={n} className={threshold===n?'selected':''} onClick={()=>setThreshold(n)}><span>{n}일 이상</span><strong>{rows.length}<small>개</small></strong><p>매입원가 {won(rows.reduce((s,i)=>s+i.purchasePrice+i.buyShipping+i.repairCost,0))}</p></button>;})}</div>
    <section className="card pricing-card"><div className="pricing-toolbar"><input aria-label="가격조정 상품 검색" placeholder="상품명·브랜드·상품코드 검색" value={search} onChange={e=>setSearch(e.target.value)}/><span>입고일 미확인 {stock.filter(i=>holdingDays(i.acquiredDate)===null).length}건</span><label>미리보기 인하율<input aria-label="미리보기 인하율" type="number" min="0" max="99" value={percent} onChange={e=>setPercent(Number(e.target.value))}/>%</label><button className="secondary" disabled={!selected.length||!Number.isFinite(percent)||percent<0||percent>=100} onClick={()=>setDrafts(d=>({...d,...Object.fromEntries(picked.filter(i=>i.listing.price||i.expectedPrice).map(i=>[i.id,Math.max(1,Math.round((i.listing.price||i.expectedPrice)*(1-percent/100)/1000)*1000)]))}))}>선택 상품 변경가 계산</button></div>
    <p className="muted">표시 가격은 원장 등록가 기준입니다. 번장 실제 시세 비교는 V5 안정화 후 진행합니다. 예상마진에는 설정 수수료와 배송비를 반영합니다.</p>
    <div className="inventory-text-wrap"><table className="inventory-text-table"><thead><tr><th><input type="checkbox" aria-label="보이는 상품 전체 선택" checked={visible.length>0&&visible.every(i=>selected.includes(i.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map(i=>i.id)])]:selected.filter(id=>!visible.some(i=>i.id===id)))}/></th><th>상품</th><th>현재 등록가</th><th>매입원가</th><th>보유기간</th><th>변경가</th><th>인하율</th><th>예상마진</th></tr></thead><tbody>{visible.map(i=>{const next=drafts[i.id],c=priceComparison(i,next??(i.listing.price||i.expectedPrice),feeRate,shipping);return <tr key={i.id}><td><input type="checkbox" aria-label={`${i.id} 선택`} checked={selected.includes(i.id)} onChange={e=>setSelected(e.target.checked?[...selected,i.id]:selected.filter(id=>id!==i.id))}/></td><td><b>{i.brand} {i.name}</b><small>{i.id}</small></td><td>{c.current?won(c.current):'미입력'}</td><td>{won(i.purchasePrice+i.buyShipping+i.repairCost)}</td><td>{holdingDays(i.acquiredDate)}일</td><td><input className="price-input" aria-label={`${i.id} 변경가`} type="number" min="1" value={next??''} placeholder="직접 입력" onChange={e=>{const value=e.target.value;setDrafts(d=>{const copy={...d};if(value==='')delete copy[i.id];else copy[i.id]=Number(value);return copy;});}}/>{next!==undefined&&next<i.minimumPrice&&<small className="negative">최저가보다 낮음</small>}</td><td>{next!==undefined&&c.cut!==null?`${c.cut.toFixed(1)}%`:'—'}</td><td className={c.margin<0?'negative':'positive'}>{next!==undefined?won(c.margin):'—'}</td></tr>;})}</tbody></table></div>
    {!visible.length&&<p className="empty">조건에 맞는 재고가 없습니다.</p>}
    <div className="price-actions"><span>{picked.length}개 선택 · 선택 상품만 검토</span><button className="secondary" disabled={!picked.length||invalid} onClick={()=>setPreview(true)}>변경 내용 미리보기</button><button className="primary" disabled={locked||!picked.length||invalid} onClick={()=>{if(!locked)onApply(drafts,selected);}}>{locked?'가격 적용 보류':'선택 상품 가격 적용'}</button></div></section>
    {preview&&<div className="drawer-backdrop center-modal"><section className="sale-modal"><h2>선택 상품 가격 미리보기</h2><p>원장과 번장 가격은 변경되지 않았습니다.</p><div className="price-preview">{picked.map(i=><p key={i.id}><span>{i.brand} {i.name}</span><b>{won(i.listing.price||i.expectedPrice)} → {won(drafts[i.id])}</b></p>)}</div><button className="secondary" onClick={()=>setPreview(false)}>닫기</button></section></div>}
  </>;
}
