import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const partsDir = resolve(root, 'build_parts');
const stylesPath = resolve(root, 'public/styles.css');
const vocabPath = resolve(root, 'data/vocabulary.json');
const cssSources = [
  "styles.css",
  "student-learning.css",
  "teacher-dashboard-v136.css",
  "v137.css",
  "v138.css",
  "v139.css",
  "v1310.css",
  "v1311.css",
  "v1313.css",
  "v1315.css",
  "v1317.css",
  "v1320.css",
  "v1321.css",
  "v1322.css",
  "v1323.css",
  "v1324.css",
  "v1325.css",
  "v1326.css",
  "v1327.css",
  "v1328.css",
  "v1329.css",
  "v1330.css",
  "v1332.css",
  "v1334.css",
  "v1337.css",
  "v1339.css",
  "v1340.css",
  "v1341.css",
  "v1344.css",
  "v1345.css",
  "v1353.css",
  "v1354.css",
  "v1358.css",
  "v1359.css",
  "v1360.css",
  "v1361.css",
  "v1362.css",
  "v1363.css",
  "v1364.css",
  "v1365.css",
  "v1366.css",
  "v1367.css",
  "v1368.css",
  "v1369.css",
  "v1370.css",
  "v1371.css",
  "v1372.css",
  "v1373.css",
  "v1374.css",
  "v1375.css",
  "v1376.css",
  "v1377.css",
  "v1378.css",
  "v1380.css",
  "v1382.css",
  "v1385.css",
  "v1386.css",
  "v13861.css",
  "v1388.css",
  "v1389.css",
  "v1390.css",
  "v1391.css",
  "v1392.css",
  "v1394.css",
  "v1395.css",
  "v1396.css",
  "v1398.css"
];
const cssBundlePath = resolve(root, 'public/app.bundle.css');


if (!existsSync(stylesPath)) {
  const styles = ['styles.00', 'styles.01']
    .map(name => readFileSync(resolve(partsDir, name), 'utf8'))
    .join('');
  writeFileSync(stylesPath, styles);
}

if (!existsSync(vocabPath)) {
  mkdirSync(dirname(vocabPath), { recursive: true });
  const chunks = readdirSync(partsDir)
    .filter(name => /^vocab\..+\.b64$/.test(name))
    .sort();
  if (!chunks.length) throw new Error('Vocabulary build parts not found');
  const encoded = chunks
    .map(name => readFileSync(resolve(partsDir, name), 'utf8'))
    .join('')
    .replace(/\s+/g, '');
  writeFileSync(vocabPath, Buffer.from(encoded, 'base64'));
}

const raw = readFileSync(vocabPath);
if (raw.length >= 2 && raw[0] === 0x1f && raw[1] === 0x8b) {
  writeFileSync(vocabPath, gunzipSync(raw));
}

const cssBundle = cssSources
  .map(name => readFileSync(resolve(root, 'public', name), 'utf8'))
  .join('\n');
writeFileSync(cssBundlePath, cssBundle);

// Service worker: precache list + a hash of every served file. Any change to
// the app changes sw.js, so installed apps pick up each deploy even when no
// version string was bumped by hand.
{
  const publicDir = resolve(root, 'public');
  const walk = dir => readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const full = resolve(dir, entry.name);
    return entry.isDirectory() ? walk(full) : [full];
  });
  const urlOf = full => '/' + full.slice(publicDir.length + 1).split(/[\\/]/).join('/');
  const legacyCss = new Set(cssSources.map(name => '/' + name));
  const served = walk(publicDir)
    .map(full => ({ full, url: urlOf(full) }))
    .filter(({ url }) => /\.(?:js|mjs|css|html|svg|webp|png|webmanifest)$/.test(url) && url !== '/sw.js' && !legacyCss.has(url))
    .sort((a, b) => a.url.localeCompare(b.url));
  const hash = createHash('sha256');
  for (const { full, url } of served) hash.update(url).update('\0').update(readFileSync(full)).update('\0');
  // Loaded on every start; teacher tools, grammar data and pet images are cached on first
  // use. Images still count toward ASSET_HASH, so a redrawn pet reaches installed apps.
  // V13.77: the install guide, its QR code and the PNG icons are also only fetched when used.
  const onDemand = /^\/(?:(?:teacher-enhancements|exam-ops|grammar-choice-sample|[a-z-]+-grammar-data|install)\.js|install\.html|vendor\/.+|icons\/.+\.png|assets\/.+\.webp)$/;
  // The page is cached as "/": Cloudflare answers /index.html with a 307 to /,
  // and a redirected response cannot be used to answer a navigation.
  const precache = served.map(({ url }) => url === '/index.html' ? '/' : url).filter(url => !onDemand.test(url));
  const swPath = resolve(publicDir, 'sw.js');
  const sw = readFileSync(swPath, 'utf8');
  const generated = `// BUILD:START (generated by server/build-assets.mjs, do not edit by hand)\nconst ASSET_HASH = '${hash.digest('hex').slice(0, 16)}';\nconst PRECACHE = ${JSON.stringify(precache)};\n// BUILD:END`;
  const next = sw.replace(/\/\/ BUILD:START[\s\S]*?\/\/ BUILD:END/, generated);
  if (next === sw && !sw.includes(generated)) throw new Error('sw.js BUILD markers not found');
  if (next !== sw) writeFileSync(swPath, next);
  console.log(`[service-worker] ${precache.length} precached files, hash ${generated.match(/ASSET_HASH = '(\w+)'/)[1]}`);
}

const validateBuild = process.env.NODE_ENV !== 'production' || process.env.RUN_BUILD_VALIDATION === 'true';
if (validateBuild) {
  const { runContentValidation } = await import('./content-validation.mjs');
  runContentValidation();
  console.log('[content-validation] PASS');

  function publicJavaScriptFiles(dir) {
    return readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
      const full = resolve(dir, entry.name);
      if (entry.isDirectory()) return publicJavaScriptFiles(full);
      return entry.isFile() && entry.name.endsWith('.js') ? [full] : [];
    });
  }

  for (const file of publicJavaScriptFiles(resolve(root, 'public'))) {
    try {
      execFileSync(process.execPath, ['--check', file], { stdio: 'pipe' });
    } catch (error) {
      const detail = String(error?.stderr || error?.stdout || error?.message || error);
      throw new Error('Browser JavaScript syntax check failed: ' + file.replace(root, '') + '\n' + detail);
    }
  }
  console.log('[browser-syntax] PASS');
} else {
  console.log('[build-assets] production runtime validation skipped; CI already validates release assets');
}
